In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/BDF8C4F3-D7B6-4D50-847F-9227A0B71B68/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Sep 01 2012',
 'Sep 08 2012',
 'Sep 15 2012',
 'Sep 22 2012',
 'Sep 29 2012',
 'Oct 05 2012',
 'Oct 13 2012',
 'Oct 20 2012',
 'Oct 27 2012',
 'Nov 03 2012',
 'Nov 17 2012']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([15652, 42257, 14264,  9461, 31765,  9878,  4800, 14867, 11373,
        3112,  6322], dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[114:357:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([138, 235, 112, 200, 201, 139, 306, 184, 158, 138, 122], dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:360:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([263, 137, 322, 157, 262, 227, 154, 311, 294, 273, 355], dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:360:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 52,  69,  24,  41,  47,  63,  56,  62,  54, 195, 101], dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:383:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([ 8, 42,  7, 37,  4,  0,  6,  0, 44,  0,  0], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:644:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([49, 66, 55, 84, 62, 67, 74, 62, 48, 72, 79], dtype=int64)

In [10]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:646:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([28, 21, 13, 52, 40, 11, 21, 15, 13, 11, 24], dtype=int64)

In [11]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:646:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([1, 3, 1, 4, 3, 3, 2, 1, 1, 1, 1], dtype=int64)

In [12]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:646:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([ 5, 20,  9, 30, 29,  6, 13,  9,  8,  7,  6], dtype=int64)

In [13]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[698:900:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([5, 8, 3, 7, 4, 5, 1, 5, 4, 6, 5], dtype=int64)

In [14]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2012=pd.DataFrame(list_of_dicts)
df2012.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2012       15652           138              263               52   
1  Sep 08 2012       42257           235              137               69   
2  Sep 15 2012       14264           112              322               24   
3  Sep 22 2012        9461           200              157               41   
4  Sep 29 2012       31765           201              262               47   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0                8          49           28         1          5        5  
1               42          66           21         3         20        8  
2                7          55           13         1          9        3  
3               37          84           52         4         30        7  
4                4          62           40         3         29        4

In [15]:
#splitting date column into month, day, & year columns 
df2012[['month','day','year']]=df2012.date.str.split(expand=True)
df2012.drop('date',axis=1)
df2012.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2012       15652           138              263               52   
1  Sep 08 2012       42257           235              137               69   
2  Sep 15 2012       14264           112              322               24   
3  Sep 22 2012        9461           200              157               41   
4  Sep 29 2012       31765           201              262               47   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0                8          49           28         1          5        5   
1               42          66           21         3         20        8   
2                7          55           13         1          9        3   
3               37          84           52         4         30        7   
4                4          62           40         3         29        4   

  month day  year  
0   Sep  01  2012  
1   Sep  08  2012  
2   Sep  15  2012  
3   Sep  22  2012  
4   Sep  29  2012

In [16]:
#create a new date variable
#change month variable to a 2 digit string variable
df2012['month'] = df2012['month'].str.replace('Aug','08')
df2012['month'] = df2012['month'].str.replace('Sep','09')
df2012['month'] = df2012['month'].str.replace('Oct','10')
df2012['month'] = df2012['month'].str.replace('Nov','11')
df2012['month'] = df2012['month'].str.replace('Dec','12')
#merge month,day and year variables
df2012['date']=df2012['year']+ '-' +df2012['month']+ '-'+df2012['day']
#make date into a datetime variable
df2012['date']= pd.to_datetime(df2012['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2012=df2012.drop(['month','day'], axis=1)
#make year numeric
df2012['year']=pd.to_numeric(df2012['year'])
df2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     int64         
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), int64(11)
memory usage: 1.2 KB


In [17]:
#sort data
df2012=df2012.sort_values('date',ignore_index=True)
df2012.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2012-09-01       15652           138              263               52   
1 2012-09-08       42257           235              137               69   
2 2012-09-15       14264           112              322               24   
3 2012-09-22        9461           200              157               41   
4 2012-09-29       31765           201              262               47   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0                8          49           28         1          5        5   
1               42          66           21         3         20        8   
2                7          55           13         1          9        3   
3               37          84           52         4         30        7   
4                4          62           40         3         29        4   

   year  
0  2012  
1  2012  
2  2012  
3  2012  
4  2012

In [18]:
#save data
df2012.to_csv('2012.csv',encoding='utf-8')