In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/26C45AE2-D036-475D-A4EF-38BE29FA4865/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:120:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date=[a.replace('10-04-14    ','Oct 04 2014') for a in date]
date

['Aug 30 2014',
 'Sep 06 2014',
 'Sep 13 2014',
 'Sep 20 2014',
 'Sep 27 2014',
 'Oct 04 2014',
 'Oct 11 2014',
 'Oct 18 2014',
 'Oct 25 2014',
 'Nov 01 2014',
 'Nov 08 2014',
 'Nov 22 2014']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:120:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([10541, 15725, 46914,  9217, 29225,  8089,  5849,  6738,  8289,
        5052,  6143,  1962], dtype=int64)

In [3]:
#get TSU rushing yard
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[124:400:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)              
TSUrushyards

array([439,  92, 137,  92, 125, 143,  43,  53, 107, 105, 111, 114],
      dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[128:400:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([ 71, 340, 187, 113, 153, 362, 364, 314, 180, 326, 395, 463],
      dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[136:400:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 77, 111,  29,   0,  24,  53,  63,  32, 136, 198,  58,  48],
      dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[140:400:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([57, 22, 40, 15, 56, 24, 12, -1,  1,  0, -2,  0], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[447:723:23]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([53, 89, 54, 48, 64, 81, 75, 73, 54, 84, 85, 81], dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[449:711:23]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([38, 28, 40, 31, 51,  9, 21, 48, 17, 19, 29, 63], dtype=int64)

In [9]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[450:711:23]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([2., 3., 7., 6., 7., 0., 2., 3., 1., 2., 2., 8.])

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[451:711:23]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([13, 13, 33, 28, 44,  0, 13, 22,  9,  4, 15, 51], dtype=int64)

In [11]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[767:981:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([1, 8, 8, 9, 7, 5, 3, 8, 6, 5, 0, 6], dtype=int64)

In [12]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2014=pd.DataFrame(list_of_dicts)
df2014.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 30 2014       10541           439               71               77   
1  Sep 06 2014       15725            92              340              111   
2  Sep 13 2014       46914           137              187               29   
3  Sep 20 2014        9217            92              113                0   
4  Sep 27 2014       29225           125              153               24   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               57          53           38       2.0         13        1  
1               22          89           28       3.0         13        8  
2               40          54           40       7.0         33        8  
3               15          48           31       6.0         28        9  
4               56          64           51       7.0         44        7

In [13]:
#splitting date column into month, day, & year columns 
df2014[['month','day','year']]=df2014.date.str.split(expand=True)
df2014.drop('date',axis=1)
df2014.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 30 2014       10541           439               71               77   
1  Sep 06 2014       15725            92              340              111   
2  Sep 13 2014       46914           137              187               29   
3  Sep 20 2014        9217            92              113                0   
4  Sep 27 2014       29225           125              153               24   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               57          53           38       2.0         13        1   
1               22          89           28       3.0         13        8   
2               40          54           40       7.0         33        8   
3               15          48           31       6.0         28        9   
4               56          64           51       7.0         44        7   

  month day  year  
0   Aug  30  2014  
1   Sep  06  2014  
2   Sep  13  2014  
3   Sep  20  2014  
4   Sep  27  2014

In [14]:
#create a new date variable
#change month variable to a 2 digit string variable
df2014['month'] = df2014['month'].str.replace('Aug','08')
df2014['month'] = df2014['month'].str.replace('Sep','09')
df2014['month'] = df2014['month'].str.replace('Oct','10')
df2014['month'] = df2014['month'].str.replace('Nov','11')
df2014['month'] = df2014['month'].str.replace('Dec','12')
#merge month,day and year variables
df2014['date']=df2014['year']+ '-' +df2014['month']+ '-'+df2014['day']
#make date into a datetime variable
df2014['date']= pd.to_datetime(df2014['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2014=df2014.drop(['month','day'], axis=1)
#make year numeric
df2014['year']=pd.to_numeric(df2014['year'])
df2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             12 non-null     datetime64[ns]
 1   attendance       12 non-null     int64         
 2   TSUrushyards     12 non-null     int64         
 3   TSUreceiveyards  12 non-null     int64         
 4   TSUkreturnyards  12 non-null     int64         
 5   TSUpreturnyards  12 non-null     int64         
 6   TSUtackles       12 non-null     int64         
 7   TSUtackleyd      12 non-null     int64         
 8   TSUsacks         12 non-null     float64       
 9   TSUsackyd        12 non-null     int64         
 10  TSUpunt          12 non-null     int64         
 11  year             12 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.2 KB


In [16]:
#sort data
df2014=df2014.sort_values('date',ignore_index=True)
df2014.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2014-08-30       10541           439               71               77   
1 2014-09-06       15725            92              340              111   
2 2014-09-13       46914           137              187               29   
3 2014-09-20        9217            92              113                0   
4 2014-09-27       29225           125              153               24   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               57          53           38       2.0         13        1   
1               22          89           28       3.0         13        8   
2               40          54           40       7.0         33        8   
3               15          48           31       6.0         28        9   
4               56          64           51       7.0         44        7   

   year  
0  2014  
1  2014  
2  2014  
3  2014  
4  2014

In [17]:
#save data
df2014.to_csv('2014.csv',encoding='utf-8')