In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/99B728E2-12D4-4887-A990-249892B83897/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Sep 03 2005',
 'Sep 10 2005',
 'Sep 17 2005',
 'Sep 24 2005',
 'Oct 01 2005',
 'Oct 13 2005',
 'Oct 22 2005',
 'Oct 29 2005',
 'Nov 05 2005',
 'Nov 12 2005',
 'Nov 19 2005']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([25342, 48300,  5263, 56297, 42310, 10226,  6490,  8278, 23481,
        2512,  4779], dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[114:357:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([ 72, 286,  77,  26, 117, 233, 157,  87,  50, 141, -18], dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:360:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([154, 103, 170, 238, 115,  78, 185, 160, 196, 286, 150], dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:360:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 62,  11, 110,  10,  99,  71, 114,  78,  90, 128, 138], dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:380:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([32, 47, -2, 67, 49, 53, 14,  3,  0,  1,  0], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:650:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([47, 59, 95, 70, 75, 89, 62, 72, 61, 53, 64], dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:650:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([20, 29, 17, 56, 56, 41,  9, 20, 26, 20,  6], dtype=int64)

In [11]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:650:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([2., 3., 1., 7., 6., 2., 0., 2., 1., 1., 0.])

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:650:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([13, 16,  6, 50, 37, 11,  0,  8, 14,  7,  0], dtype=int64)

In [12]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[698:900:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([4, 3, 6, 6, 6, 8, 5, 7, 5, 5, 8], dtype=int64)

In [13]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2005=pd.DataFrame(list_of_dicts)
df2005.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 03 2005       25342            72              154               62   
1  Sep 10 2005       48300           286              103               11   
2  Sep 17 2005        5263            77              170              110   
3  Sep 24 2005       56297            26              238               10   
4  Oct 01 2005       42310           117              115               99   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               32          47           20       2.0         13        4  
1               47          59           29       3.0         16        3  
2               -2          95           17       1.0          6        6  
3               67          70           56       7.0         50        6  
4               49          75           56       6.0         37        6

In [14]:

#splitting date column into month, day, & year columns 
df2005[['month','day','year']]=df2005.date.str.split(expand=True)
df2005.drop('date',axis=1)
df2005.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 03 2005       25342            72              154               62   
1  Sep 10 2005       48300           286              103               11   
2  Sep 17 2005        5263            77              170              110   
3  Sep 24 2005       56297            26              238               10   
4  Oct 01 2005       42310           117              115               99   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               32          47           20       2.0         13        4   
1               47          59           29       3.0         16        3   
2               -2          95           17       1.0          6        6   
3               67          70           56       7.0         50        6   
4               49          75           56       6.0         37        6   

  month day  year  
0   Sep  03  2005  
1   Sep  10  2005  
2   Sep  17  2005  
3   Sep  24  2005  
4   Oct  01  2005

In [15]:
#create a new date variable
#change month variable to a 2 digit string variable
df2005['month'] = df2005['month'].str.replace('Aug','08')
df2005['month'] = df2005['month'].str.replace('Sep','09')
df2005['month'] = df2005['month'].str.replace('Oct','10')
df2005['month'] = df2005['month'].str.replace('Nov','11')
df2005['month'] = df2005['month'].str.replace('Dec','12')
#merge month,day and year variables
df2005['date']=df2005['year']+ '-' +df2005['month']+ '-'+df2005['day']
#make date into a datetime variable
df2005['date']= pd.to_datetime(df2005['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2005=df2005.drop(['month','day'], axis=1)
#make year numeric
df2005['year']=pd.to_numeric(df2005['year'])
df2005.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     float64       
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.2 KB
