In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/57C54C44-DE63-4F94-99EB-2BB3329FC2BA/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace('2003','2004') for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date=[a.replace(" 4"," 04") for a in date]
date

['Sep 04 2004',
 'Sep 09 2004',
 'Sep 18 2004',
 'Sep 25 2004',
 'Oct 02 2004',
 'Oct 16 2004',
 'Oct 23 2004',
 'Oct 30 2004',
 'Nov 06 2004',
 'Nov 13 2004',
 'Nov 20 2004']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([25117,  7019, 55015, 67712, 51082, 14722,  5041,  5422, 23421,
        7100,  4864], dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[114:357:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([152, 156, 164, 161,  22, 106, 290,  22, 243, 194,  83], dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:360:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([203, 158, 149, 163, 173, 381, 211, 192, 215, 162, 142], dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:360:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 24,  34,  39,  49,  57, 120, 127, 100,  76,  95, 130], dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:380:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([26, 32, 10, 32,  0,  0, 36, 77, 22, 63,  0], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:650:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([74, 65, 63, 78, 91, 77, 88, 66, 63, 67, 66], dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:650:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([35, 60, 19, 70, 17,  0, 23,  6, 31, 25, 16], dtype=int64)

In [9]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:650:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([2., 4., 2., 5., 1., 0., 1., 0., 2., 1., 0.])

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:650:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([12, 30,  7, 49,  4,  0,  5,  0, 12,  5,  0], dtype=int64)

In [11]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[698:900:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([4, 7, 7, 9, 9, 4, 4, 8, 7, 6, 8], dtype=int64)

In [12]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2004=pd.DataFrame(list_of_dicts)
df2004.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 04 2004       25117           152              203               24   
1  Sep 09 2004        7019           156              158               34   
2  Sep 18 2004       55015           164              149               39   
3  Sep 25 2004       67712           161              163               49   
4  Oct 02 2004       51082            22              173               57   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               26          74           35       2.0         12        4  
1               32          65           60       4.0         30        7  
2               10          63           19       2.0          7        7  
3               32          78           70       5.0         49        9  
4                0          91           17       1.0          4        9

In [13]:
#splitting date column into month, day, & year columns 
df2004[['month','day','year']]=df2004.date.str.split(expand=True)
df2004.drop('date',axis=1)
df2004.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 04 2004       25117           152              203               24   
1  Sep 09 2004        7019           156              158               34   
2  Sep 18 2004       55015           164              149               39   
3  Sep 25 2004       67712           161              163               49   
4  Oct 02 2004       51082            22              173               57   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               26          74           35       2.0         12        4   
1               32          65           60       4.0         30        7   
2               10          63           19       2.0          7        7   
3               32          78           70       5.0         49        9   
4                0          91           17       1.0          4        9   

  month day  year  
0   Sep  04  2004  
1   Sep  09  2004  
2   Sep  18  2004  
3   Sep  25  2004  
4   Oct  02  2004

In [14]:
#create a new date variable
#change month variable to a 2 digit string variable
df2004['month'] = df2004['month'].str.replace('Aug','08')
df2004['month'] = df2004['month'].str.replace('Sep','09')
df2004['month'] = df2004['month'].str.replace('Oct','10')
df2004['month'] = df2004['month'].str.replace('Nov','11')
df2004['month'] = df2004['month'].str.replace('Dec','12')
#merge month,day and year variables
df2004['date']=df2004['year']+ '-' +df2004['month']+ '-'+df2004['day']
#make date into a datetime variable
df2004['date']= pd.to_datetime(df2004['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2004=df2004.drop(['month','day'], axis=1)
#make year numeric
df2004['year']=pd.to_numeric(df2004['year'])
df2004.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     float64       
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.2 KB


In [15]:
#sort data
df2004=df2004.sort_values('date',ignore_index=True)
df2004.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2004-09-04       25117           152              203               24   
1 2004-09-09        7019           156              158               34   
2 2004-09-18       55015           164              149               39   
3 2004-09-25       67712           161              163               49   
4 2004-10-02       51082            22              173               57   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               26          74           35       2.0         12        4   
1               32          65           60       4.0         30        7   
2               10          63           19       2.0          7        7   
3               32          78           70       5.0         49        9   
4                0          91           17       1.0          4        9   

   year  
0  2004  
1  2004  
2  2004  
3  2004  
4  2004

In [16]:
#save data frame to folder
df2004.to_csv('2004.csv',encoding='utf-8')