In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/E394BBB1-387B-4C6A-9B21-E33D34956811/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:140:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Sep 01 2013',
 'Sep 07 2013',
 'Sep 14 2013',
 'Sep 21 2013',
 'Sep 28 2013',
 'Oct 05 2013',
 'Oct 12 2013',
 'Oct 19 2013',
 'Oct 26 2013',
 'Nov 02 2013',
 'Nov 16 2013',
 'Nov 09 2013',
 'Nov 30 2013',
 'Dec 07 2013']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:140:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([16108, 14237, 42400, 10044, 22000,  7374, 19092,  4166, 22157,
        5700,  6412,  5258,  1928,  4825], dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[144:446:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([116, 268, 174,  95, 311, 264, 215,  69, 126,  71, 241, 146, 152,
        45], dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[148:466:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([132, 131, 111, 343, 228, 280, 133, 170, 212, 101,  60, 173, 263,
       242], dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[156:460:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 84, 111,  64,  63,  46,  24,  48,  64,  19,  96,  45,   8,  -9,
        52], dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[160:460:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([51, 17, 11, 23, 75,  7, 46,  0, 56, -1, 19, 13, -3,  2],
      dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[513:800:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([62, 41, 69, 76, 70, 37, 70, 78, 70, 63, 54, 60, 47, 73],
      dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[515:822:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([ 7, 35, 26, 51, 44, 12, 61, 56, 31,  3, 31, 59, 21, 13],
      dtype=int64)

In [9]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[516:822:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([1., 3., 2., 3., 3., 1., 5., 5., 3., 0., 3., 5., 2., 1.])

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[517:822:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([ 4, 18, 13, 28, 17,  8, 18, 35, 27,  0, 20, 37,  7,  5],
      dtype=int64)

In [11]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[863:1119:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([5, 4, 3, 5, 1, 3, 6, 6, 8, 9, 8, 5, 4, 8], dtype=int64)

In [12]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2013=pd.DataFrame(list_of_dicts)
df2013.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2013       16108           116              132               84   
1  Sep 07 2013       14237           268              131              111   
2  Sep 14 2013       42400           174              111               64   
3  Sep 21 2013       10044            95              343               63   
4  Sep 28 2013       22000           311              228               46   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               51          62            7       1.0          4        5  
1               17          41           35       3.0         18        4  
2               11          69           26       2.0         13        3  
3               23          76           51       3.0         28        5  
4               75          70           44       3.0         17        1

In [13]:
#splitting date column into month, day, & year columns 
df2013[['month','day','year']]=df2013.date.str.split(expand=True)
df2013.drop('date',axis=1)
df2013.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2013       16108           116              132               84   
1  Sep 07 2013       14237           268              131              111   
2  Sep 14 2013       42400           174              111               64   
3  Sep 21 2013       10044            95              343               63   
4  Sep 28 2013       22000           311              228               46   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               51          62            7       1.0          4        5   
1               17          41           35       3.0         18        4   
2               11          69           26       2.0         13        3   
3               23          76           51       3.0         28        5   
4               75          70           44       3.0         17        1   

  month day  year  
0   Sep  01  2013  
1   Sep  07  2013  
2   Sep  14  2013  
3   Sep  21  2013  
4   Sep  28  2013

In [14]:
#create a new date variable
#change month variable to a 2 digit string variable
df2013['month'] = df2013['month'].str.replace('Aug','08')
df2013['month'] = df2013['month'].str.replace('Sep','09')
df2013['month'] = df2013['month'].str.replace('Oct','10')
df2013['month'] = df2013['month'].str.replace('Nov','11')
df2013['month'] = df2013['month'].str.replace('Dec','12')
#merge month,day and year variables
df2013['date']=df2013['year']+ '-' +df2013['month']+ '-'+df2013['day']
#make date into a datetime variable
df2013['date']= pd.to_datetime(df2013['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2013=df2013.drop(['month','day'], axis=1)
#make year numeric
df2013['year']=pd.to_numeric(df2013['year'])
df2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             14 non-null     datetime64[ns]
 1   attendance       14 non-null     int64         
 2   TSUrushyards     14 non-null     int64         
 3   TSUreceiveyards  14 non-null     int64         
 4   TSUkreturnyards  14 non-null     int64         
 5   TSUpreturnyards  14 non-null     int64         
 6   TSUtackles       14 non-null     int64         
 7   TSUtackleyd      14 non-null     int64         
 8   TSUsacks         14 non-null     float64       
 9   TSUsackyd        14 non-null     int64         
 10  TSUpunt          14 non-null     int64         
 11  year             14 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.4 KB


In [15]:
#sort data
df2013=df2013.sort_values('date',ignore_index=True)
df2013.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2013-09-01       16108           116              132               84   
1 2013-09-07       14237           268              131              111   
2 2013-09-14       42400           174              111               64   
3 2013-09-21       10044            95              343               63   
4 2013-09-28       22000           311              228               46   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               51          62            7       1.0          4        5   
1               17          41           35       3.0         18        4   
2               11          69           26       2.0         13        3   
3               23          76           51       3.0         28        5   
4               75          70           44       3.0         17        1   

   year  
0  2013  
1  2013  
2  2013  
3  2013  
4  2013

In [16]:
#save data
df2013.to_csv('2013.csv',encoding='utf-8')