In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/125803E8-C113-4C2F-890C-645D4ED8B38B/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:90:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date=[a.strip() for a in date]
date=[a.replace('11-03-18' ,'Nov 03 2018') for a in date]
date

['Sep 01 2018',
 'Sep 22 2018',
 'Sep 29 2018',
 'Oct 06 2018',
 'Oct 13 2018',
 'Oct 20 2018',
 'Nov 03 2018',
 'Nov 10 2018',
 'Nov 17 2018']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:90:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([14069,  7670, 27340, 12201,  3318, 17283,  3481,  6718,  3618],
      dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[94:300:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([201, 195, 104, 164,  63, 149, 253, 178,  89], dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[98:300:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([324, 349, 269, 325, 307, 323, 255, 164, 170], dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[106:300:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 49, 150, 105, 134, 140,  48,  78,  36,  63], dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[110:300:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([64, 51,  3, 34, -1, 14,  0,  0, 29], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[348:546:23]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([54, 63, 69, 77, 74, 77, 65, 60, 64], dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[350:546:23]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([43, 30,  5, 19, 19, 28, 28, 27, 38], dtype=int64)

In [9]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[351:540:23]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([5., 2., 0., 0., 1., 4., 2., 2., 2.])

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[352:540:23]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([35, 15,  0,  0,  7, 21, 14, 19, 18], dtype=int64)

In [11]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[599:769:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([6, 4, 4, 4, 5, 4, 3, 5, 7], dtype=int64)

In [12]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2018=pd.DataFrame(list_of_dicts)
df2018.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2018       14069           201              324               49   
1  Sep 22 2018        7670           195              349              150   
2  Sep 29 2018       27340           104              269              105   
3  Oct 06 2018       12201           164              325              134   
4  Oct 13 2018        3318            63              307              140   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               64          54           43       5.0         35        6  
1               51          63           30       2.0         15        4  
2                3          69            5       0.0          0        4  
3               34          77           19       0.0          0        4  
4               -1          74           19       1.0          7        5

In [13]:
#splitting date column into month, day, & year columns 
df2018[['month','day','year']]=df2018.date.str.split(expand=True)
df2018.drop('date',axis=1)
df2018.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2018       14069           201              324               49   
1  Sep 22 2018        7670           195              349              150   
2  Sep 29 2018       27340           104              269              105   
3  Oct 06 2018       12201           164              325              134   
4  Oct 13 2018        3318            63              307              140   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               64          54           43       5.0         35        6   
1               51          63           30       2.0         15        4   
2                3          69            5       0.0          0        4   
3               34          77           19       0.0          0        4   
4               -1          74           19       1.0          7        5   

  month day  year  
0   Sep  01  2018  
1   Sep  22  2018  
2   Sep  29  2018  
3   Oct  06  2018  
4   Oct  13  2018

In [14]:
#create a new date variable
#change month variable to a 2 digit string variable
df2018['month'] = df2018['month'].str.replace('Aug','08')
df2018['month'] = df2018['month'].str.replace('Sep','09')
df2018['month'] = df2018['month'].str.replace('Oct','10')
df2018['month'] = df2018['month'].str.replace('Nov','11')
df2018['month'] = df2018['month'].str.replace('Dec','12')
#merge month,day and year variables
df2018['date']=df2018['year']+ '-' +df2018['month']+ '-'+df2018['day']
#make date into a datetime variable
df2018['date']= pd.to_datetime(df2018['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2018=df2018.drop(['month','day'], axis=1)
#make year numeric
df2018['year']=pd.to_numeric(df2018['year'])
df2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             9 non-null      datetime64[ns]
 1   attendance       9 non-null      int64         
 2   TSUrushyards     9 non-null      int64         
 3   TSUreceiveyards  9 non-null      int64         
 4   TSUkreturnyards  9 non-null      int64         
 5   TSUpreturnyards  9 non-null      int64         
 6   TSUtackles       9 non-null      int64         
 7   TSUtackleyd      9 non-null      int64         
 8   TSUsacks         9 non-null      float64       
 9   TSUsackyd        9 non-null      int64         
 10  TSUpunt          9 non-null      int64         
 11  year             9 non-null      int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 992.0 bytes


In [15]:
#sort values
df2018=df2018.sort_values('date',ignore_index=True)
df2018.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2018-09-01       14069           201              324               49   
1 2018-09-22        7670           195              349              150   
2 2018-09-29       27340           104              269              105   
3 2018-10-06       12201           164              325              134   
4 2018-10-13        3318            63              307              140   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               64          54           43       5.0         35        6   
1               51          63           30       2.0         15        4   
2                3          69            5       0.0          0        4   
3               34          77           19       0.0          0        4   
4               -1          74           19       1.0          7        5   

   year  
0  2018  
1  2018  
2  2018  
3  2018  
4  2018

In [16]:
#save data
df2018.to_csv('2018.csv',encoding='utf-8')