In [29]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/1EEBECA9-B01E-43AB-B6EB-AFDBF863957B/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Aug 31 2017',
 'Sep 09 2017',
 'Sep 17 2017',
 'Sep 23 2017',
 'Sep 30 2017',
 'Oct 07 2017',
 'Oct 14 2017',
 'Oct 28 2017',
 'Nov 04 2017',
 'Nov 11 2017',
 'Nov 16 2017']

In [30]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([24333, 47407, 17102,  6484, 11013,  8410, 21127,  5235,  7487,
        8693, 18782], dtype=int64)

In [31]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[114:346:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([238, 160, 241, 100,  83, 193, 106,  83, 174, 147,  15], dtype=int64)

In [32]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:369:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([145,  78, 273, 159, 195, 106, 208, 331, 274, 196,  82], dtype=int64)

In [33]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:363:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 44,  49,  63, 160,  48,  25,  64, 135,  18, 103, 140], dtype=int64)

In [34]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:363:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([ 0, 41,  7,  3,  0, -3, 13, -2, 94, 29,  1], dtype=int64)

In [35]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:646:23]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([59, 76, 38, 77, 73, 60, 61, 62, 41, 57, 71], dtype=int64)

In [36]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:660:23]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([26, 21, 19, 21, 14,  8, 11, 28, 45, 14, 18], dtype=int64)

In [37]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:660:23]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([3., 4., 0., 1., 0., 1., 1., 1., 6., 1., 1.])

In [38]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:660:23]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([17, 18,  0,  5,  0,  1,  0,  9, 34,  5,  9], dtype=int64)

In [39]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[711:919:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([ 5,  6,  2,  6,  6,  5,  4,  4,  3,  4, 11], dtype=int64)

In [40]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2017=pd.DataFrame(list_of_dicts)
df2017.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 31 2017       24333           238              145               44   
1  Sep 09 2017       47407           160               78               49   
2  Sep 17 2017       17102           241              273               63   
3  Sep 23 2017        6484           100              159              160   
4  Sep 30 2017       11013            83              195               48   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0                0          59           26       3.0         17        5  
1               41          76           21       4.0         18        6  
2                7          38           19       0.0          0        2  
3                3          77           21       1.0          5        6  
4                0          73           14       0.0          0        6

In [41]:
#splitting date column into month, day, & year columns 
df2017[['month','day','year']]=df2017.date.str.split(expand=True)
df2017.drop('date',axis=1)
df2017.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 31 2017       24333           238              145               44   
1  Sep 09 2017       47407           160               78               49   
2  Sep 17 2017       17102           241              273               63   
3  Sep 23 2017        6484           100              159              160   
4  Sep 30 2017       11013            83              195               48   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0                0          59           26       3.0         17        5   
1               41          76           21       4.0         18        6   
2                7          38           19       0.0          0        2   
3                3          77           21       1.0          5        6   
4                0          73           14       0.0          0        6   

  month day  year  
0   Aug  31  2017  
1   Sep  09  2017  
2   Sep  17  2017  
3   Sep  23  2017  
4   Sep  30  2017

In [42]:
#create a new date variable
#change month variable to a 2 digit string variable
df2017['month'] = df2017['month'].str.replace('Aug','08')
df2017['month'] = df2017['month'].str.replace('Sep','09')
df2017['month'] = df2017['month'].str.replace('Oct','10')
df2017['month'] = df2017['month'].str.replace('Nov','11')
df2017['month'] = df2017['month'].str.replace('Dec','12')
#merge month,day and year variables
df2017['date']=df2017['year']+ '-' +df2017['month']+ '-'+df2017['day']
#make date into a datetime variable
df2017['date']= pd.to_datetime(df2017['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2017=df2017.drop(['month','day'], axis=1)
#make year numeric
df2017['year']=pd.to_numeric(df2017['year'])
df2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     float64       
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.2 KB
