In [48]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/F8A9B17C-4555-45FB-AAF3-D88956A7F089/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date=[a.replace( '11-19-16    ','Nov 19 2016') for a in date]
date

['Sep 03 2016',
 'Sep 10 2016',
 'Sep 17 2016',
 'Oct 01 2016',
 'Oct 08 2016',
 'Oct 15 2016',
 'Oct 22 2016',
 'Oct 29 2016',
 'Nov 05 2016',
 'Nov 12 2016',
 'Nov 19 2016']

In [49]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([15078, 46263,  9385, 10001,  4319, 21053, 31084,  8605,  6041,
        8981,  3117], dtype=int64)

In [50]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[113:346:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([38, 30, 44, 37, 35, 40, 23, 39, 24, 28, 40], dtype=int64)

In [51]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:369:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([259, 273, 184, 223, 303, 181, 285, 329, 212, 202, 279], dtype=int64)

In [52]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:363:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([ 29,  96, 122,  80, 113,  78,  59, 142,  86,  93,  93], dtype=int64)

In [53]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:363:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([64, 11, 23,  0,  0,  0,  0, 10, 14, 17, 17], dtype=int64)

In [54]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:646:23]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([52, 61, 52, 63, 75, 74, 65, 74, 90, 53, 69], dtype=int64)

In [55]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:660:23]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([39, 40, 17, 28,  6, 14,  6, 20, 24,  2, 36], dtype=int64)

In [56]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:660:23]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([5., 3., 1., 2., 1., 0., 1., 2., 2., 1., 3.])

In [57]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:660:23]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([31, 21,  1, 12,  3,  0,  5, 14, 13,  0, 26], dtype=int64)

In [58]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[711:919:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([3, 6, 5, 1, 5, 3, 3, 2, 5, 3, 3], dtype=int64)

In [59]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2016=pd.DataFrame(list_of_dicts)
df2016.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 03 2016       15078            38              259               29   
1  Sep 10 2016       46263            30              273               96   
2  Sep 17 2016        9385            44              184              122   
3  Oct 01 2016       10001            37              223               80   
4  Oct 08 2016        4319            35              303              113   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               64          52           39       5.0         31        3  
1               11          61           40       3.0         21        6  
2               23          52           17       1.0          1        5  
3                0          63           28       2.0         12        1  
4                0          75            6       1.0          3        5

In [60]:
#splitting date column into month, day, & year columns 
df2016[['month','day','year']]=df2016.date.str.split(expand=True)
df2016.drop('date',axis=1)
df2016.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 03 2016       15078            38              259               29   
1  Sep 10 2016       46263            30              273               96   
2  Sep 17 2016        9385            44              184              122   
3  Oct 01 2016       10001            37              223               80   
4  Oct 08 2016        4319            35              303              113   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               64          52           39       5.0         31        3   
1               11          61           40       3.0         21        6   
2               23          52           17       1.0          1        5   
3                0          63           28       2.0         12        1   
4                0          75            6       1.0          3        5   

  month day  year  
0   Sep  03  2016  
1   Sep  10  2016  
2   Sep  17  2016  
3   Oct  01  2016  
4   Oct  08  2016

In [61]:
#create a new date variable
#change month variable to a 2 digit string variable
df2016['month'] = df2016['month'].str.replace('Aug','08')
df2016['month'] = df2016['month'].str.replace('Sep','09')
df2016['month'] = df2016['month'].str.replace('Oct','10')
df2016['month'] = df2016['month'].str.replace('Nov','11')
df2016['month'] = df2016['month'].str.replace('Dec','12')
#merge month,day and year variables
df2016['date']=df2016['year']+ '-' +df2016['month']+ '-'+df2016['day']
#make date into a datetime variable
df2016['date']= pd.to_datetime(df2016['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2016=df2016.drop(['month','day'], axis=1)
#make year numeric
df2016['year']=pd.to_numeric(df2016['year'])
df2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     float64       
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(10)
memory usage: 1.2 KB
