In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/4C48DA5B-76BE-4378-8E95-9BB2B0DE5E20/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:110:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Sep 01 2007',
 'Sep 08 2007',
 'Sep 15 2007',
 'Sep 22 2007',
 'Sep 29 2007',
 'Oct 11 2007',
 'Oct 20 2007',
 'Oct 27 2007',
 'Nov 03 2007',
 'Nov 08 2007',
 'Nov 17 2007']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:110:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([23440, 50879,  8359, 15371, 56990,  9369, 11500,  8935, 24878,
        4193,  7859], dtype=int64)

In [4]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[114:357:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([206, 153, 238, 133, 177, 320, 169, 166, 280, 187, 290], dtype=int64)

In [5]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[118:360:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([176, 232, 233, 316, 309, 138, 127, 189,  69, 125, 173], dtype=int64)

In [6]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[126:360:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([154,  84,  83, 135, 111,  64, 122,  84,   6,  94, 222], dtype=int64)

In [7]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[130:380:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([35, 24, 14, 15, 33,  8,  0, 20, 77, -1, 31], dtype=int64)

In [8]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[414:650:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([56, 63, 64, 80, 78, 70, 77, 88, 93, 75, 92], dtype=int64)

In [9]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[416:650:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([17, 30, 44, 56, 28, 23, 19, 12, 25, 35, 14], dtype=int64)

In [10]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[417:650:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([2, 2, 3, 3, 3, 0, 1, 0, 3, 1, 1], dtype=int64)

In [11]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[418:650:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([15, 16, 26, 36, 23,  0, 10,  0, 15, 11,  8], dtype=int64)

In [12]:
#TSU punts
TSUpunt=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[698:900:19]
TSUpunt=[a.replace("\xa0","") for a in TSUpunt]
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([ 6,  5,  3,  7,  4,  4, 10,  5,  3,  5,  3], dtype=int64)

In [13]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt,}
df2007=pd.DataFrame(list_of_dicts)
df2007.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2007       23440           206              176              154   
1  Sep 08 2007       50879           153              232               84   
2  Sep 15 2007        8359           238              233               83   
3  Sep 22 2007       15371           133              316              135   
4  Sep 29 2007       56990           177              309              111   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0               35          56           17         2         15        6  
1               24          63           30         2         16        5  
2               14          64           44         3         26        3  
3               15          80           56         3         36        7  
4               33          78           28         3         23        4

In [14]:
#splitting date column into month, day, & year columns 
df2007[['month','day','year']]=df2007.date.str.split(expand=True)
df2007.drop('date',axis=1)
df2007.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Sep 01 2007       23440           206              176              154   
1  Sep 08 2007       50879           153              232               84   
2  Sep 15 2007        8359           238              233               83   
3  Sep 22 2007       15371           133              316              135   
4  Sep 29 2007       56990           177              309              111   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0               35          56           17         2         15        6   
1               24          63           30         2         16        5   
2               14          64           44         3         26        3   
3               15          80           56         3         36        7   
4               33          78           28         3         23        4   

  month day  year  
0   Sep  01  2007  
1   Sep  08  2007  
2   Sep  15  2007  
3   Sep  22  2007  
4   Sep  29  2007

In [15]:
#create a new date variable
#change month variable to a 2 digit string variable
df2007['month'] = df2007['month'].str.replace('Aug','08')
df2007['month'] = df2007['month'].str.replace('Sep','09')
df2007['month'] = df2007['month'].str.replace('Oct','10')
df2007['month'] = df2007['month'].str.replace('Nov','11')
df2007['month'] = df2007['month'].str.replace('Dec','12')
#merge month,day and year variables
df2007['date']=df2007['year']+ '-' +df2007['month']+ '-'+df2007['day']
#make date into a datetime variable
df2007['date']= pd.to_datetime(df2007['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2007=df2007.drop(['month','day'], axis=1)
#make year numeric
df2007['year']=pd.to_numeric(df2007['year'])
df2007.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             11 non-null     datetime64[ns]
 1   attendance       11 non-null     int64         
 2   TSUrushyards     11 non-null     int64         
 3   TSUreceiveyards  11 non-null     int64         
 4   TSUkreturnyards  11 non-null     int64         
 5   TSUpreturnyards  11 non-null     int64         
 6   TSUtackles       11 non-null     int64         
 7   TSUtackleyd      11 non-null     int64         
 8   TSUsacks         11 non-null     int64         
 9   TSUsackyd        11 non-null     int64         
 10  TSUpunt          11 non-null     int64         
 11  year             11 non-null     int64         
dtypes: datetime64[ns](1), int64(11)
memory usage: 1.2 KB
