In [1]:
#libraries to use
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
#python's lxml library parses xml and html files
from lxml import html

#use requests to get data from web pages
import requests 

#use requests.get() to get web page with data
page = requests.get('https://tennstate_ftp.sidearmsports.com/custompages/tsutigers/E0564A83-37A0-4B85-8811-B7EFB00E956D/teamgbg.htm')

#parse data on web page using html module.fromstring
mytree = html.fromstring(page.content)

#go to web address above , right click on page and select inspect to get HTML code for data from right side of page
#create XPath query and use xpath function to get data
#date data
date = mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[1:120:10]
date=[a.replace("\xa0","") for a in date]
date=[a.replace(",","") for a in date]
date=[a.replace(".","") for a in date]
date

['Aug 30 2008',
 'Sep 06 2008',
 'Sep 13 2008',
 'Sep 20 2008',
 'Sep 27 2008',
 'Oct 04 2008',
 'Oct 18 2008',
 'Oct 25 2008',
 'Nov 01 2008',
 'Nov 08 2008',
 'Nov 15 2008',
 'Nov 22 2008']

In [2]:
#get attendance data
attendance=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[9:120:10]
attendance=[a.replace("\xa0","") for a in attendance]
attendance=[a.strip() for a in attendance]
attendance=pd.to_numeric(attendance)
attendance

array([10072, 28830, 50794,  8276, 50428,  7549,  9358,  9750, 24361,
        6393,  7956,  2292], dtype=int64)

In [3]:
#get TSU rushing yards
TSUrushyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[124:380:23]
TSUrushyards=[a.replace("\xa0","") for a in TSUrushyards]
TSUrushyards=pd.to_numeric(TSUrushyards)
TSUrushyards

array([107, 148, 148, 229, 136, 177, 377, 217, 212, 309, 177, 113],
      dtype=int64)

In [4]:
#get TSU receiving yards
TSUreceiveyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[128:383:23]
TSUreceiveyards=[a.replace("\xa0","") for a in TSUreceiveyards]
TSUreceiveyards=pd.to_numeric(TSUreceiveyards)
TSUreceiveyards

array([292, 315, 137, 314, 241, 155, 108, 233, 138, 162, 170, 210],
      dtype=int64)

In [5]:
#get TSU kick return yards
TSUkreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[136:406:23]
TSUkreturnyards=[a.replace("\xa0","") for a in TSUkreturnyards]
TSUkreturnyards=pd.to_numeric(TSUkreturnyards)
TSUkreturnyards

array([160,  66,  34,  84,  95,  93, 101,  72,  32,  59,  57,  57],
      dtype=int64)

In [6]:
#get TSU punt return yards
TSUpreturnyards=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[140:403:23]
TSUpreturnyards=[a.replace("\xa0","") for a in TSUpreturnyards]
TSUpreturnyards=pd.to_numeric(TSUpreturnyards)
TSUpreturnyards

array([ 2, 37, 38,  6,  2, 21,  0, 18, 37,  4, 42, -2], dtype=int64)

In [7]:
#get TSU total tackles
TSUtackles=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[447:694:22]
TSUtackles=[a.replace("\xa0","") for a in TSUtackles]
TSUtackles=pd.to_numeric(TSUtackles)
TSUtackles

array([46, 76, 58, 51, 61, 74, 62, 54, 67, 68, 69, 60], dtype=int64)

In [8]:
#get TSU tackle yards
TSUtackleyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[449:694:22]
TSUtackleyd=[a.replace("\xa0","") for a in TSUtackleyd]
TSUtackleyd=pd.to_numeric(TSUtackleyd)
TSUtackleyd

array([20, 29,  9, 48, 37, 13, 25, 27, 30, 19, 10, 26], dtype=int64)

In [9]:
#get TSU sacks
TSUsacks=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[450:694:22]
TSUsacks=[a.replace("\xa0","") for a in TSUsacks]
TSUsacks=pd.to_numeric(TSUsacks)
TSUsacks

array([1, 1, 0, 3, 3, 0, 2, 2, 2, 2, 1, 2], dtype=int64)

In [10]:
#get TSU sack yards
TSUsackyd=mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[451:694:22]
TSUsackyd=[a.replace("\xa0","") for a in TSUsackyd]
TSUsackyd=pd.to_numeric(TSUsackyd)
TSUsackyd

array([10,  4,  0, 27, 23,  0, 22, 15, 16, 13,  8, 11], dtype=int64)

In [11]:
#TSU punts
TSUpunt=[]
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[753][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[772][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[791][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[810][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[829][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[848][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[867][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[886][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[905][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[924][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[943][0])
TSUpunt.append(mytree.xpath('body/center//tr/td/font[@color="#000000"]/text()')[962][0])
TSUpunt=pd.to_numeric(TSUpunt)
TSUpunt

array([3, 3, 3, 3, 5, 6, 1, 1, 4, 4, 7, 5], dtype=int64)

In [12]:
#create data frame
#change dictionary of lists to data frame
list_of_dicts={'date':date,
     'attendance':attendance,
     'TSUrushyards':TSUrushyards,
     'TSUreceiveyards':TSUreceiveyards,
     'TSUkreturnyards':TSUkreturnyards,
     'TSUpreturnyards':TSUpreturnyards,
     'TSUtackles':TSUtackles,
     'TSUtackleyd':TSUtackleyd,
     'TSUsacks':TSUsacks,
     'TSUsackyd':TSUsackyd,
     'TSUpunt':TSUpunt}
df2008=pd.DataFrame(list_of_dicts)
df2008.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 30 2008       10072           107              292              160   
1  Sep 06 2008       28830           148              315               66   
2  Sep 13 2008       50794           148              137               34   
3  Sep 20 2008        8276           229              314               84   
4  Sep 27 2008       50428           136              241               95   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  
0                2          46           20         1         10        3  
1               37          76           29         1          4        3  
2               38          58            9         0          0        3  
3                6          51           48         3         27        3  
4                2          61           37         3         23        5

In [13]:
#splitting date column into month, day, & year columns 
df2008[['month','day','year']]=df2008.date.str.split(expand=True)
df2008.drop('date',axis=1)
df2008.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0  Aug 30 2008       10072           107              292              160   
1  Sep 06 2008       28830           148              315               66   
2  Sep 13 2008       50794           148              137               34   
3  Sep 20 2008        8276           229              314               84   
4  Sep 27 2008       50428           136              241               95   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0                2          46           20         1         10        3   
1               37          76           29         1          4        3   
2               38          58            9         0          0        3   
3                6          51           48         3         27        3   
4                2          61           37         3         23        5   

  month day  year  
0   Aug  30  2008  
1   Sep  06  2008  
2   Sep  13  2008  
3   Sep  20  2008  
4   Sep  27  2008

In [14]:
#create a new date variable
#change month variable to a 2 digit string variable
df2008['month'] = df2008['month'].str.replace('Aug','08')
df2008['month'] = df2008['month'].str.replace('Sep','09')
df2008['month'] = df2008['month'].str.replace('Oct','10')
df2008['month'] = df2008['month'].str.replace('Nov','11')
df2008['month'] = df2008['month'].str.replace('Dec','12')
#merge month,day and year variables
df2008['date']=df2008['year']+ '-' +df2008['month']+ '-'+df2008['day']
#make date into a datetime variable
df2008['date']= pd.to_datetime(df2008['date'], format='%Y-%m-%d')
#drop individual month,day, variables (keep year variable for later analysis)
df2008=df2008.drop(['month','day'], axis=1)
#make year numeric
df2008['year']=pd.to_numeric(df2008['year'])
df2008.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   date             12 non-null     datetime64[ns]
 1   attendance       12 non-null     int64         
 2   TSUrushyards     12 non-null     int64         
 3   TSUreceiveyards  12 non-null     int64         
 4   TSUkreturnyards  12 non-null     int64         
 5   TSUpreturnyards  12 non-null     int64         
 6   TSUtackles       12 non-null     int64         
 7   TSUtackleyd      12 non-null     int64         
 8   TSUsacks         12 non-null     int64         
 9   TSUsackyd        12 non-null     int64         
 10  TSUpunt          12 non-null     int64         
 11  year             12 non-null     int64         
dtypes: datetime64[ns](1), int64(11)
memory usage: 1.2 KB


In [16]:
#sort data
df2008=df2008.sort_values('date',ignore_index=True)
df2008.head()

date  attendance  TSUrushyards  TSUreceiveyards  TSUkreturnyards  \
0 2008-08-30       10072           107              292              160   
1 2008-09-06       28830           148              315               66   
2 2008-09-13       50794           148              137               34   
3 2008-09-20        8276           229              314               84   
4 2008-09-27       50428           136              241               95   

   TSUpreturnyards  TSUtackles  TSUtackleyd  TSUsacks  TSUsackyd  TSUpunt  \
0                2          46           20         1         10        3   
1               37          76           29         1          4        3   
2               38          58            9         0          0        3   
3                6          51           48         3         27        3   
4                2          61           37         3         23        5   

   year  
0  2008  
1  2008  
2  2008  
3  2008  
4  2008

In [17]:
#save data
df2008.to_csv('2008.csv',encoding='utf-8')